# Generated by Django 4.0.4 on 2022-05-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_frequencycontent_frequencytitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='MediaScr',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
